package com.leetsync.backend.service;

import com.leetsync.backend.dto.*;
import com.leetsync.backend.exception.ApiException;
import com.leetsync.backend.github.GitHubClient;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

@Service
public class GitHubSyncService {

    private final GitHubClient githubClient;
    private final CodeFileService codeFileService;
    private final SubmissionFormatter formatter;

    public GitHubSyncService(GitHubClient githubClient,
                             CodeFileService codeFileService,
                             SubmissionFormatter formatter) {
        this.githubClient = githubClient;
        this.codeFileService = codeFileService;
        this.formatter = formatter;
    }

    public SyncResponse sync(String token, String owner, SubmissionRequest request) {

        // Only accepted submissions should reach GitHub.
        if (request.accepted() != null && !request.accepted()) {
            throw new ApiException(
                    HttpStatus.BAD_REQUEST,
                    "NOT_ACCEPTED",
                    "Only accepted submissions can be synchronized."
            );
        }

        if (request.repository() == null || request.repository().isBlank()) {
            throw new ApiException(
                    HttpStatus.BAD_REQUEST,
                    "MISSING_REPOSITORY",
                    "repository is required."
            );
        }

        String repo = request.repository();

        // Verify that the repository exists and determine its default branch.
        GitHubRepositoryResponse repository =
                githubClient.getRepository(token, owner, repo);

        String branch = request.branch() == null || request.branch().isBlank()
                ? repository.defaultBranch()
                : request.branch();

        // Generate paths for this problem.
        String solutionPath = codeFileService.path(request);
        System.out.println("SYNC SOLUTION PATH = " + solutionPath);
        String problemReadmePath = codeFileService.problemReadmePath(request);

        // Check whether this problem already exists.
        GitHubContentsResponse existingSolution =
                githubClient.getFile(token, owner, repo, solutionPath, branch);

        GitHubContentsResponse existingProblemReadme =
                githubClient.getFile(token, owner, repo, problemReadmePath, branch);

        boolean isNewProblem = existingProblemReadme == null
                || existingProblemReadme.content() == null;

        String formattedCode = formatter.format(request);

        // Handle the solution file.
        if (existingSolution == null || existingSolution.content() == null) {

            String message = buildCommitMessage(request, false);

            GitHubPutFileRequest putRequest = new GitHubPutFileRequest(
                    message,
                    encode(formattedCode),
                    branch,
                    null
            );

            GitHubPutFileResponse result =
                    githubClient.putFile(
                            token,
                            owner,
                            repo,
                            solutionPath,
                            putRequest
                    );

            String sha = extractCommitSha(result);

            // New problem: create its README and update global stats.
            if (isNewProblem) {
                createOrUpdateProblemReadme(
                        token,
                        owner,
                        repo,
                        request,
                        branch,
                        null
                );

                updateRootReadme(
                        token,
                        owner,
                        repo,
                        request,
                        branch,
                        true
                );
            }

            return new SyncResponse(
                    "CREATED",
                    message,
                    solutionPath,
                    sha,
                    true
            );
        }

        // Decode the existing GitHub file.
        String existingFile = decode(existingSolution.content());

        /*
         * The metadata header is generated by SubmissionFormatter.
         * We compare the actual source code separately from the metadata.
         */
        String existingCode = formatter.extractCode(existingFile);

        // Exact same source code = never create a duplicate commit.
        if (existingCode.equals(normalizeCode(request.code()))) {
            return SyncResponse.skipped(
                    "Exact same solution already exists; no duplicate commit created.",
                    solutionPath
            );
        }

        /*
         * Different code:
         *
         * If performance information is available, only replace the
         * existing solution when the new solution is demonstrably
         * better based on the available metrics.
         *
         * If no performance information is available, we allow the
         * different solution to be stored.
         */
        boolean shouldUpdate = shouldUpdateSolution(request, existingFile);

        if (!shouldUpdate) {
            return SyncResponse.skipped(
                    "Different solution found, but the existing solution is not outperformed.",
                    solutionPath
            );
        }

        String message = buildCommitMessage(request, true);

        GitHubPutFileRequest putRequest = new GitHubPutFileRequest(
                message,
                encode(formattedCode),
                branch,
                existingSolution.sha()
        );

        GitHubPutFileResponse result =
                githubClient.putFile(
                        token,
                        owner,
                        repo,
                        solutionPath,
                        putRequest
                );

        String sha = extractCommitSha(result);

        /*
         * The problem already existed, so the global count must NOT
         * increase. We only update the problem README if necessary.
         */
        if (!isNewProblem) {
            createOrUpdateProblemReadme(
                    token,
                    owner,
                    repo,
                    request,
                    branch,
                    existingProblemReadme
            );
        }

        return new SyncResponse(
                "UPDATED",
                message,
                solutionPath,
                sha,
                true
        );
    }

    private void createOrUpdateProblemReadme(
            String token,
            String owner,
            String repo,
            SubmissionRequest request,
            String branch,
            GitHubContentsResponse existingReadme
    ) {
        String path = codeFileService.problemReadmePath(request);

        String content = "# "
                + request.problemId()
                + ". "
                + request.problemTitle()
                + "\n\n"
                + "- Source: " + request.source() + "\n"
                + "- Language: " + request.language() + "\n";

        GitHubPutFileRequest putRequest = new GitHubPutFileRequest(
                "Update README: " + request.problemId() + ". " + request.problemTitle(),
                encode(content),
                branch,
                existingReadme == null ? null : existingReadme.sha()
        );

        githubClient.putFile(
                token,
                owner,
                repo,
                path,
                putRequest
        );
    }

    private void updateRootReadme(
            String token,
            String owner,
            String repo,
            SubmissionRequest request,
            String branch,
            boolean newProblem
    ) {
        String path = "README.md";

        GitHubContentsResponse existingRootReadme =
                githubClient.getFile(token, owner, repo, path, branch);

        int solvedCount = 0;

        if (existingRootReadme != null && existingRootReadme.content() != null) {
            String existingContent = decode(existingRootReadme.content());

            java.util.regex.Pattern pattern =
                    java.util.regex.Pattern.compile(
                            "Global stats:\\s*(\\d+)\\s+Problem[s]?\\s+Solved",
                            java.util.regex.Pattern.CASE_INSENSITIVE
                    );

            java.util.regex.Matcher matcher = pattern.matcher(existingContent);

            if (matcher.find()) {
                solvedCount = Integer.parseInt(matcher.group(1));
            }
        }

        if (newProblem) {
            solvedCount++;
        }

        String problemWord = solvedCount == 1 ? "Problem" : "Problems";

        String content =
                "# My LeetCode Solutions\n\n"
                        + "Global stats: "
                        + solvedCount
                        + " "
                        + problemWord
                        + " Solved\n";

        GitHubPutFileRequest putRequest = new GitHubPutFileRequest(
                "Update global stats",
                encode(content),
                branch,
                existingRootReadme == null ? null : existingRootReadme.sha()
        );

        githubClient.putFile(
                token,
                owner,
                repo,
                path,
                putRequest
        );
    }

    /**
     * Determines whether a new solution should replace the existing one.
     *
     * Runtime and memory are treated independently:
     *
     * - If both are available, the new solution must be no worse in either
     *   metric and strictly better in at least one.
     * - If only runtime is available, runtime must improve.
     * - If only memory is available, memory must improve.
     * - If neither metric is available, a different solution is accepted.
     */
    private boolean shouldUpdateSolution(
            SubmissionRequest request,
            String existingFile
    ) {

        Performance existingPerformance =
                extractPerformance(existingFile);

        Double newRuntime = request.runtimePercentile();
        Double newMemory = request.memoryPercentile();

        /*
         * No percentile information on the new submission.
         * We cannot make a performance comparison, so allow a
         * genuinely different solution to be stored.
         */
        if (newRuntime == null && newMemory == null) {
            return true;
        }

        /*
         * No performance information was stored in the old file.
         * Since we have nothing meaningful to compare against,
         * allow the new solution.
         */
        if (existingPerformance.runtime == null
                && existingPerformance.memory == null) {
            return true;
        }

        /*
         * Both runtime and memory are available.
         *
         * Percentile is "Beats X%".
         * Higher percentile = better performance.
         */
        if (newRuntime != null && newMemory != null
                && existingPerformance.runtime != null
                && existingPerformance.memory != null) {

            boolean runtimeAtLeastAsGood =
                    newRuntime >= existingPerformance.runtime;

            boolean memoryAtLeastAsGood =
                    newMemory >= existingPerformance.memory;

            boolean strictlyBetter =
                    newRuntime > existingPerformance.runtime
                            || newMemory > existingPerformance.memory;

            return runtimeAtLeastAsGood
                    && memoryAtLeastAsGood
                    && strictlyBetter;
        }

        /*
         * Only runtime is available on both sides.
         */
        if (newRuntime != null && existingPerformance.runtime != null) {
            return newRuntime > existingPerformance.runtime;
        }

        /*
         * Only memory is available on both sides.
         */
        if (newMemory != null && existingPerformance.memory != null) {
            return newMemory > existingPerformance.memory;
        }

        /*
         * We have a metric on one side but not the other.
         * There isn't enough information for a meaningful
         * performance comparison, so allow the new solution.
         */
        return true;
    }

    private Performance extractPerformance(String file) {
        Double runtime = extractPercentile(file, "// Runtime:");
        Double memory = extractPercentile(file, "// Memory:");

        return new Performance(runtime, memory);
    }

    /**
     * Extracts a percentile from lines such as:
     *
     * // Runtime: 3 ms | Beats 98.2%
     * // Memory: 45 MB | Beats 80.1%
     */
    private Double extractPercentile(String file, String prefix) {

        for (String line : file.split("\n")) {

            if (!line.startsWith(prefix)) {
                continue;
            }

            int beatsIndex = line.indexOf("Beats ");

            if (beatsIndex == -1) {
                return null;
            }

            String value = line.substring(beatsIndex + "Beats ".length())
                    .replace("%", "")
                    .trim();

            try {
                return Double.parseDouble(value);
            } catch (NumberFormatException ignored) {
                return null;
            }
        }

        return null;
    }

    private String normalizeCode(String code) {
        return code.replace("\r\n", "\n").trim();
    }

    private String encode(String value) {
        return Base64.getEncoder()
                .encodeToString(value.getBytes(StandardCharsets.UTF_8));
    }

    private String decode(String base64) {
        String normalized = base64.replaceAll("\\s", "");

        return new String(
                Base64.getDecoder().decode(normalized),
                StandardCharsets.UTF_8
        );
    }

    private String buildCommitMessage(
            SubmissionRequest request,
            boolean update
    ) {
        String verb = update ? "Updated" : "Solved";

        return "Auto-commit: "
                + verb
                + " "
                + request.problemId()
                + ". "
                + request.problemTitle();
    }

    private String extractCommitSha(GitHubPutFileResponse result) {

        if (result == null || result.commit() == null) {
            return null;
        }

        return result.commit().sha();
    }

    private record Performance(
            Double runtime,
            Double memory
    ) {
    }
}