spring:
  application:
    name: leetsync-backend

  jackson:
    default-property-inclusion: non_null

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/leetsync}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origin-patterns: "fgjmmopppjdfipibiliohhhoebjifmia"

  github:
    api-base-url: "https://api.github.com"
    user-agent: "LeetSync-Spring-Boot"
    default-branch: "main"